//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjaxClient.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IScheduleService")]
    public interface IScheduleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleService/GetJobs", ReplyAction="http://tempuri.org/IScheduleService/GetJobsResponse")]
        string[] GetJobs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleService/GetJobs", ReplyAction="http://tempuri.org/IScheduleService/GetJobsResponse")]
        System.Threading.Tasks.Task<string[]> GetJobsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleService/ScheduleJob", ReplyAction="http://tempuri.org/IScheduleService/ScheduleJobResponse")]
        string ScheduleJob(string type, System.Collections.Generic.Dictionary<string, string> values);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleService/ScheduleJob", ReplyAction="http://tempuri.org/IScheduleService/ScheduleJobResponse")]
        System.Threading.Tasks.Task<string> ScheduleJobAsync(string type, System.Collections.Generic.Dictionary<string, string> values);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IScheduleServiceChannel : AjaxClient.ServiceReference.IScheduleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScheduleServiceClient : System.ServiceModel.ClientBase<AjaxClient.ServiceReference.IScheduleService>, AjaxClient.ServiceReference.IScheduleService {
        
        public ScheduleServiceClient() {
        }
        
        public ScheduleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ScheduleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScheduleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScheduleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetJobs() {
            return base.Channel.GetJobs();
        }
        
        public System.Threading.Tasks.Task<string[]> GetJobsAsync() {
            return base.Channel.GetJobsAsync();
        }
        
        public string ScheduleJob(string type, System.Collections.Generic.Dictionary<string, string> values) {
            return base.Channel.ScheduleJob(type, values);
        }
        
        public System.Threading.Tasks.Task<string> ScheduleJobAsync(string type, System.Collections.Generic.Dictionary<string, string> values) {
            return base.Channel.ScheduleJobAsync(type, values);
        }
    }
}
